site_name: <%=app.name%>
site_url: <%=app.homepage%>
repo_url: https://github.com/<%=app.githubUser%>/<%=app.name%>/
site_description: <%=app.description%>
site_author: <%=app.authorName%>
site_favicon: media/favicon.ico
copyright: Copyright Â© <%=app.createdAt.split('/')[2]%> <%=app.authorName%>

theme: mkdocs #readthedocs
docs_dir: src
site_dir: ../build/mkdocs

pages:
 - 'Home': index.md
 - 'Contribution': contribution.md
 - 'Documentation': documentation.md
 - 'Changes': changes.md
